"""add today_count and today_date to goodness

Revision ID: 086be4e3b118
Revises: 0001
Create Date: 2026-03-03 18:25:33.601579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '086be4e3b118'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goodness', sa.Column('today_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('goodness', sa.Column('today_date', sa.Date(), nullable=False, server_default=sa.text('CURRENT_DATE')))
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_column('goodness', 'today_date')
    op.drop_column('goodness', 'today_count')
    # ### end Alembic commands ###
